### ISSUE TITLE
Doesn’t load void worlds

### ISSUE THREAD

**Issue by Tuvqlu** [vecnavium-pm-pl/LoadEveryWorlds#3]
**Describe the bug**
Doesn’t load worlds with generation void

**To Reproduce**
Create a world with generation void, and reload:

**Expected behavior**
My void worlds to load.
**LoadEveryWorlds plugin information**

- Plugin Version: [e.g. 1.0.1]

**Comment by Vecnavium** [comment]
This isn't exactly a plugin issue it's due to MultiWorld starting up after LoadEveryWorlds and the startup order messes it up. Restarting your server a second time if the error occurs will sort the error you are facing.
