### ISSUE TITLE
Does not load all maps

### ISSUE THREAD

**Issue by MrBlasyMSK** [vecnavium-pm-pl/LoadEveryWorlds#5]
**Describe the bug**
```
[20:27:58.231] [Server thread/INFO]: Loading LoadEveryWorlds v1.0.1
[20:27:58.237] [Server thread/ERROR]: Could not load world "End": Unknown generator "ender"
[20:27:58.257] [Server thread/INFO]: Preparing world "4,-16"
[20:27:58.270] [Server thread/INFO]: [LoadEveryWorlds] World Lobby has been loaded
[20:27:58.274] [Server thread/ERROR]: Could not load world "Nether": Unknown generator "nether_mw"
[20:27:58.285] [Server thread/ERROR]: Could not load world "Parcelas": Unknown generator "myplot"
```
There is nothing to describe, it does not load all worlds.

**To Reproduce**
Generate myplot world and check if can load it

**Expected behavior**
Expected to load all
**LoadEveryWorlds plugin information**
- Plugin Version: Dev14

**Screenshots**
X

**Additional context**
X

**Comment by JavierLeon9966** [comment]
It cannot load those wolds because the generator is unknown according to that error. This is expected behavior and not a bug

**Comment by JavierLeon9966** [comment]
To fix that you would just need a plugin that register those generators

**Comment by MrBlasyMSK** [comment]
> To fix that you would just need a plugin that register those generators

Currently there is none updated, that's why I report this bug, besides the plugin is supposed to "load all worlds".
Obviously you are not going to ask it to load a map from version 1.18 but if it doesn't load the most used ones (like myplot or multiworld), it is not much use.

**Comment by JavierLeon9966** [comment]
To load those worlds from MyPlot and MultiWorld it requires you to install those plugins. This plugin won’t install those plugins for you if that’s what you expect.

**Comment by JavierLeon9966** [comment]
Only certain worlds can be loaded if you have a certain plugin, and those worlds from MyPlot can only be loaded if you have MyPlot, the same logic goes to MultiWorld worlds

**Comment by MrBlasyMSK** [comment]
> Only certain worlds can be loaded if you have a certain plugin, and those worlds from MyPlot can only be loaded if you have MyPlot, the same logic goes to MultiWorld worlds

Yes, but if you create a plugin called "LoadEveryWorlds" and also add in features: "Load all your worlds without the need of commands" then you expect that plugin to load all the worlds you have on your server (I think it has enough logic) and if not he can add a Disclaimer on the readme like: "This plugin does not support worlds generated by MyPlot or MultiWorld"

**Comment by Vecnavium** [comment]
This plugin loads all the worlds and has been tested with MultiWorld before and it loads the world generated by MultiWorld with no issues on my end and I haven't been reported this issue so often at all by other users and you are like the 3rd one ever since the plugin was released. To further talk about the issue on exactly how to reproduce it you can communicate with me on Vecnavium's Community Discord which is in the README.md.
